//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/InputBindings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputBindings: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputBindings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputBindings"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""8032b4e0-ea07-448e-a46f-826428218e93"",
            ""actions"": [
                {
                    ""name"": ""MouseGaze"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7b0bda95-acbb-4d86-bfc4-068e87d5f99b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EyeTracking"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4d0b5468-84ff-45ab-8a1b-f6b4bcbc76a9"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eye Gaze Is Tracked"",
                    ""type"": ""Button"",
                    ""id"": ""06a9a29a-909b-478e-9d80-9db6477b58a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeadPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""75707510-0e30-4dde-99ea-d63b588b76e7"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeadRotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7cf1e19c-6229-4845-91b2-224ef0394189"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Controller Device"",
                    ""type"": ""PassThrough"",
                    ""id"": ""710cac6c-f52f-4e35-9b78-a311e942af66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Controller Device"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cc3f1646-d3bb-4f6e-ba45-e79e6432c891"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1145d288-c1de-48ff-a9ba-6a41974a1b7e"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseGaze"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e8e4604-9ad6-45e8-8bae-aac704d73f72"",
                    ""path"": ""<EyeGaze>/pose/rotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""EyeTracking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d52bcb8-884c-4ec6-a540-62eb821b34af"",
                    ""path"": ""<XRInputV1::EyeTrackingOpenXR>/pose/isTracked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eye Gaze Is Tracked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7faa211c-44f0-454e-baa7-892372c3c995"",
                    ""path"": ""<OpenXRHmd>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""HeadPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e41562f-8087-41b7-a641-180aa5f992be"",
                    ""path"": ""<OpenXRHmd>/centerEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""HeadRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d959c47-6ddd-407f-aacb-0d16de4e8427"",
                    ""path"": ""<XRController>{LeftHand}/{Device}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""Left Controller Device"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83d3da9e-ffd3-428e-833e-d90482557b66"",
                    ""path"": ""<XRController>{RightHand}/{Device}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""VR"",
                    ""action"": ""Right Controller Device"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""d0613ba3-3bef-4e31-a113-db450867f0f2"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""9f48518a-c72a-4dd0-b42a-0a6039298806"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""6a0112b9-3336-421b-8bcf-3c130dd30550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""25a282cc-a9fc-4158-8351-1dfe84d4ccf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""58caaec9-d7b5-4e62-b67a-1c89ccfd0981"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""startrecordingtest"",
                    ""type"": ""Button"",
                    ""id"": ""cd90c677-250d-488a-b874-25896e7dff15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""stoprecordingtest"",
                    ""type"": ""Button"",
                    ""id"": ""37d78d2a-1e32-4ead-bf3c-e868a8a90fcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""showrecordingtest"",
                    ""type"": ""Button"",
                    ""id"": ""074bee3f-6141-4743-8603-5417aefa121a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46fb3456-afd2-488e-ab59-d3933a80c822"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d12c2f81-d972-4f8a-bd4a-d9c3c072068a"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a47a8031-9228-44e9-a1b5-c2ad9758addc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""905a6251-40fe-4195-851e-e47d798602a8"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a274a355-f0d4-40c1-8a2d-b9f621bfd34e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74ca1241-1141-4afa-b3d5-9f541a91814d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4bb9e23-0873-40d7-9414-388e6caa172e"",
                    ""path"": ""<XRController>/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9b80497-afb5-488d-9654-04b1c55e3e73"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""startrecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7300ca3-d4db-4d23-870e-e138f21e1abf"",
                    ""path"": ""<XRInputV1::Oculus::OculusTouchControllerOpenXR>{LeftHand}/secondarybutton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""startrecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb8bfe4c-19ce-495a-a1be-6627d34ba8ef"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stoprecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fee7c1e-33ef-400d-9d58-1ec9cccb2c79"",
                    ""path"": ""<XRInputV1::Oculus::OculusTouchControllerOpenXR>{LeftHand}/primarybutton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stoprecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0387bae-2ff1-492c-a6eb-561dea198a3b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""showrecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""474c08c7-e738-4ba5-8417-70bd170f7ed6"",
                    ""path"": ""<XRInputV1::Oculus::OculusTouchControllerOpenXR>{LeftHand}/thumbstickclicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""showrecordingtest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""VR"",
            ""bindingGroup"": ""VR"",
            ""devices"": []
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MouseGaze = m_Player.FindAction("MouseGaze", throwIfNotFound: true);
        m_Player_EyeTracking = m_Player.FindAction("EyeTracking", throwIfNotFound: true);
        m_Player_EyeGazeIsTracked = m_Player.FindAction("Eye Gaze Is Tracked", throwIfNotFound: true);
        m_Player_HeadPosition = m_Player.FindAction("HeadPosition", throwIfNotFound: true);
        m_Player_HeadRotation = m_Player.FindAction("HeadRotation", throwIfNotFound: true);
        m_Player_LeftControllerDevice = m_Player.FindAction("Left Controller Device", throwIfNotFound: true);
        m_Player_RightControllerDevice = m_Player.FindAction("Right Controller Device", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Continue = m_UI.FindAction("Continue", throwIfNotFound: true);
        m_UI_Return = m_UI.FindAction("Return", throwIfNotFound: true);
        m_UI_Skip = m_UI.FindAction("Skip", throwIfNotFound: true);
        m_UI_Select = m_UI.FindAction("Select", throwIfNotFound: true);
        m_UI_startrecordingtest = m_UI.FindAction("startrecordingtest", throwIfNotFound: true);
        m_UI_stoprecordingtest = m_UI.FindAction("stoprecordingtest", throwIfNotFound: true);
        m_UI_showrecordingtest = m_UI.FindAction("showrecordingtest", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_MouseGaze;
    private readonly InputAction m_Player_EyeTracking;
    private readonly InputAction m_Player_EyeGazeIsTracked;
    private readonly InputAction m_Player_HeadPosition;
    private readonly InputAction m_Player_HeadRotation;
    private readonly InputAction m_Player_LeftControllerDevice;
    private readonly InputAction m_Player_RightControllerDevice;
    public struct PlayerActions
    {
        private @InputBindings m_Wrapper;
        public PlayerActions(@InputBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseGaze => m_Wrapper.m_Player_MouseGaze;
        public InputAction @EyeTracking => m_Wrapper.m_Player_EyeTracking;
        public InputAction @EyeGazeIsTracked => m_Wrapper.m_Player_EyeGazeIsTracked;
        public InputAction @HeadPosition => m_Wrapper.m_Player_HeadPosition;
        public InputAction @HeadRotation => m_Wrapper.m_Player_HeadRotation;
        public InputAction @LeftControllerDevice => m_Wrapper.m_Player_LeftControllerDevice;
        public InputAction @RightControllerDevice => m_Wrapper.m_Player_RightControllerDevice;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @MouseGaze.started += instance.OnMouseGaze;
            @MouseGaze.performed += instance.OnMouseGaze;
            @MouseGaze.canceled += instance.OnMouseGaze;
            @EyeTracking.started += instance.OnEyeTracking;
            @EyeTracking.performed += instance.OnEyeTracking;
            @EyeTracking.canceled += instance.OnEyeTracking;
            @EyeGazeIsTracked.started += instance.OnEyeGazeIsTracked;
            @EyeGazeIsTracked.performed += instance.OnEyeGazeIsTracked;
            @EyeGazeIsTracked.canceled += instance.OnEyeGazeIsTracked;
            @HeadPosition.started += instance.OnHeadPosition;
            @HeadPosition.performed += instance.OnHeadPosition;
            @HeadPosition.canceled += instance.OnHeadPosition;
            @HeadRotation.started += instance.OnHeadRotation;
            @HeadRotation.performed += instance.OnHeadRotation;
            @HeadRotation.canceled += instance.OnHeadRotation;
            @LeftControllerDevice.started += instance.OnLeftControllerDevice;
            @LeftControllerDevice.performed += instance.OnLeftControllerDevice;
            @LeftControllerDevice.canceled += instance.OnLeftControllerDevice;
            @RightControllerDevice.started += instance.OnRightControllerDevice;
            @RightControllerDevice.performed += instance.OnRightControllerDevice;
            @RightControllerDevice.canceled += instance.OnRightControllerDevice;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @MouseGaze.started -= instance.OnMouseGaze;
            @MouseGaze.performed -= instance.OnMouseGaze;
            @MouseGaze.canceled -= instance.OnMouseGaze;
            @EyeTracking.started -= instance.OnEyeTracking;
            @EyeTracking.performed -= instance.OnEyeTracking;
            @EyeTracking.canceled -= instance.OnEyeTracking;
            @EyeGazeIsTracked.started -= instance.OnEyeGazeIsTracked;
            @EyeGazeIsTracked.performed -= instance.OnEyeGazeIsTracked;
            @EyeGazeIsTracked.canceled -= instance.OnEyeGazeIsTracked;
            @HeadPosition.started -= instance.OnHeadPosition;
            @HeadPosition.performed -= instance.OnHeadPosition;
            @HeadPosition.canceled -= instance.OnHeadPosition;
            @HeadRotation.started -= instance.OnHeadRotation;
            @HeadRotation.performed -= instance.OnHeadRotation;
            @HeadRotation.canceled -= instance.OnHeadRotation;
            @LeftControllerDevice.started -= instance.OnLeftControllerDevice;
            @LeftControllerDevice.performed -= instance.OnLeftControllerDevice;
            @LeftControllerDevice.canceled -= instance.OnLeftControllerDevice;
            @RightControllerDevice.started -= instance.OnRightControllerDevice;
            @RightControllerDevice.performed -= instance.OnRightControllerDevice;
            @RightControllerDevice.canceled -= instance.OnRightControllerDevice;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Continue;
    private readonly InputAction m_UI_Return;
    private readonly InputAction m_UI_Skip;
    private readonly InputAction m_UI_Select;
    private readonly InputAction m_UI_startrecordingtest;
    private readonly InputAction m_UI_stoprecordingtest;
    private readonly InputAction m_UI_showrecordingtest;
    public struct UIActions
    {
        private @InputBindings m_Wrapper;
        public UIActions(@InputBindings wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_UI_Continue;
        public InputAction @Return => m_Wrapper.m_UI_Return;
        public InputAction @Skip => m_Wrapper.m_UI_Skip;
        public InputAction @Select => m_Wrapper.m_UI_Select;
        public InputAction @startrecordingtest => m_Wrapper.m_UI_startrecordingtest;
        public InputAction @stoprecordingtest => m_Wrapper.m_UI_stoprecordingtest;
        public InputAction @showrecordingtest => m_Wrapper.m_UI_showrecordingtest;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Continue.started += instance.OnContinue;
            @Continue.performed += instance.OnContinue;
            @Continue.canceled += instance.OnContinue;
            @Return.started += instance.OnReturn;
            @Return.performed += instance.OnReturn;
            @Return.canceled += instance.OnReturn;
            @Skip.started += instance.OnSkip;
            @Skip.performed += instance.OnSkip;
            @Skip.canceled += instance.OnSkip;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @startrecordingtest.started += instance.OnStartrecordingtest;
            @startrecordingtest.performed += instance.OnStartrecordingtest;
            @startrecordingtest.canceled += instance.OnStartrecordingtest;
            @stoprecordingtest.started += instance.OnStoprecordingtest;
            @stoprecordingtest.performed += instance.OnStoprecordingtest;
            @stoprecordingtest.canceled += instance.OnStoprecordingtest;
            @showrecordingtest.started += instance.OnShowrecordingtest;
            @showrecordingtest.performed += instance.OnShowrecordingtest;
            @showrecordingtest.canceled += instance.OnShowrecordingtest;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Continue.started -= instance.OnContinue;
            @Continue.performed -= instance.OnContinue;
            @Continue.canceled -= instance.OnContinue;
            @Return.started -= instance.OnReturn;
            @Return.performed -= instance.OnReturn;
            @Return.canceled -= instance.OnReturn;
            @Skip.started -= instance.OnSkip;
            @Skip.performed -= instance.OnSkip;
            @Skip.canceled -= instance.OnSkip;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @startrecordingtest.started -= instance.OnStartrecordingtest;
            @startrecordingtest.performed -= instance.OnStartrecordingtest;
            @startrecordingtest.canceled -= instance.OnStartrecordingtest;
            @stoprecordingtest.started -= instance.OnStoprecordingtest;
            @stoprecordingtest.performed -= instance.OnStoprecordingtest;
            @stoprecordingtest.canceled -= instance.OnStoprecordingtest;
            @showrecordingtest.started -= instance.OnShowrecordingtest;
            @showrecordingtest.performed -= instance.OnShowrecordingtest;
            @showrecordingtest.canceled -= instance.OnShowrecordingtest;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_VRSchemeIndex = -1;
    public InputControlScheme VRScheme
    {
        get
        {
            if (m_VRSchemeIndex == -1) m_VRSchemeIndex = asset.FindControlSchemeIndex("VR");
            return asset.controlSchemes[m_VRSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMouseGaze(InputAction.CallbackContext context);
        void OnEyeTracking(InputAction.CallbackContext context);
        void OnEyeGazeIsTracked(InputAction.CallbackContext context);
        void OnHeadPosition(InputAction.CallbackContext context);
        void OnHeadRotation(InputAction.CallbackContext context);
        void OnLeftControllerDevice(InputAction.CallbackContext context);
        void OnRightControllerDevice(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnStartrecordingtest(InputAction.CallbackContext context);
        void OnStoprecordingtest(InputAction.CallbackContext context);
        void OnShowrecordingtest(InputAction.CallbackContext context);
    }
}
